name: Chrome
on:
  workflow_dispatch:
    inputs:
      extension-id:
        description: 'The ID of the Chrome extension to install'
        required: true
jobs:
  chrome:
    runs-on: ubuntu-24.04
    steps:
      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - run: |
          timeout 30s chrome
            --log-net-log=chrome-net-export-log.json
            --net-log-capture-mode=Everything
            https://example.com || true
     
