name: Chrome
on:
  workflow_dispatch:
    inputs:
      extension:
        description: 'The ID of the Chrome extension to install'
        required: true
jobs:
  chrome:
    runs-on: ubuntu-24.04
    permissions:
      actions: write
    steps:
      - name: Cache Chrome User Data Directory
        uses: actions/cache@v4
        with:
          path: chrome-user-data
          key: ${{ github.event.inputs.extension }}
      - name: Reset Chrome User Data Directory
        run: |
          rm chrome-user-data/SingletonLock || true
      - name: Force Extension Installation
        run: |
          mkdir -p /usr/share/google-chrome/extensions/
          echo '{ "external_update_url": "https://clients2.google.com/service/update2/crx" }' > /usr/share/google-chrome/extensions/${{ github.event.inputs.extension }}.json
      - name: Run Google Chrome
        run: >-
          xvfb-run
          --auto-servernum
          --server-args="-screen 0 1280x800x24 -ac -nolisten tcp -dpi 96 +extension RANDR"
          timeout 15s google-chrome
          --disable-gpu
          --no-sandbox
          --disable-setuid-sandbox
          --log-net-log=chrome-net-export-log.json
          --net-log-capture-mode=Everything
          --user-data-dir=chrome-user-data
          https://example.com || true
      - name: Upload chrome://net-export Log
        uses: actions/upload-artifact@v4
        with:
          name: chrome-net-export-log
          compression-level: 9
          path: chrome-net-export-log.json
      - name: Delete Chrome User Data Cache
        run: |
          gh extension install actions/gh-actions-cache
          gh actions-cache delete ${{ github.event.inputs.extension }} || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
