name: Chrome
on:
  workflow_dispatch:
    inputs:
      extension-id:
        description: 'The ID of the Chrome extension to install'
        required: true
jobs:
  chrome:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
     
