name: Chrome
on:
  workflow_dispatch:
    inputs:
      extension:
        description: 'The ID of the Chrome extension to install'
        required: true
jobs:
  chrome:
    runs-on: ubuntu-24.04
    steps:
      - run: |
          mkdir -p /usr/share/google-chrome/extensions/
          echo '{ "external_update_url": "https://clients2.google.com/service/update2/crx" }' > /usr/share/google-chrome/extensions/${{ github.event.inputs.extension }}.json
      - run: >-
          xvfb-run
          --auto-servernum
          --server-args="-screen 0 1280x800x24 -ac -nolisten tcp -dpi 96 +extension RANDR"
          timeout 30s google-chrome
          --disable-gpu
          --no-sandbox
          --disable-setuid-sandbox
          --log-net-log=chrome-net-export-log.json
          --net-log-capture-mode=Everything
          https://example.com || true
      - run: >
          ls -lah chrome-net-export-log.json
     
