name: Chrome
on:
  workflow_dispatch:
    inputs:
      extension-id:
        description: 'The ID of the Chrome extension to install'
        required: true
jobs:
  chrome:
    runs-on: ubuntu-24.04
    steps:
      - run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - run: |
          DISPLAY=':99.0' timeout 30s google-chrome
            --log-net-log=chrome-net-export-log.json
            --net-log-capture-mode=Everything
            https://example.com || true
     
